# Generated by Django 2.2.1 on 2019-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('client_profession', models.CharField(max_length=100)),
            ],
        ),
    ]
